lang: en

title: "Megan Pokal - Data Science Portfolio"
tagline: Megan Pokal Data Analyst
description: "Data Science, Machine Learning, and Big Data Projects."

baseurl: "/Megan-Pokal-Portfolio"
url: "https://mvpokal.github.io"

remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0

force_theme: light

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

navbar:
  - name: Home
    link: /

  - name: Projects
    link: /projects/

  - name: TSA Project
    link: /tsa-complaints/

  - name: Contact
    link: /contact/

sass:
  style: compressed
  source_dir: _sass

markdown: kramdown
highlighter: rouge
