lang: en

title: "Megan Pokal - Data Science Portfolio"
description: "Data Science, Machine Learning, and Big Data Projects"

baseurl: "/Megan-Pokal-Portfolio"
url: "https://mvpokal.github.io"

remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

navbar:
  - name: Home
    link: "{{ site.baseurl }}/"

  - name: Projects
    link: "{{ site.baseurl }}/projects/"

  - name: TSA Project
    link: "{{ site.baseurl }}/tsa-complaints/"

  - name: Contact
    link: "{{ site.baseurl }}/contact/"

markdown: kramdown
highlighter: rouge
